name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v3
    - name: Install ImageMagick
      run: |
          git clone https://github.com/ImageMagick/ImageMagick.git
          cd ImageMagick*
          # Jump to latest stable ImageMagick 7 version.
          # This might break someday, but then someone can just fix it :D
          git checkout $(git tag --sort=creatordate | grep "^7" | tail -n1)
          ./configure --with-magick-plus-plus=no --with-perl=no 
          make -j
          sudo make install
          sudo apt update && sudo apt install -y libmagickwand-dev
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
