name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v3
    - name: Install ImageMagick
      run: |
          sudo apt update && sudo apt install -y libmagickwand-dev
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
